### ISSUE TITLE
Progress / cancellation support?

### ISSUE THREAD

**Issue by yrashk** [hucsmn/qbsdiff#6]
Is there any appetite to enable (optional) support for (at the very least) support for cancellation (something similar to https://github.com/wez/cancel-rs or any other approach that'd work well) and potentially progress reporting (to enable progress tracking for potential cancellation)?

I am happy to try and contribute if that's of interest.

**Comment by hucsmn** [comment]
I have measured a [flamegraph](https://gist.githubusercontent.com/hucsmn/7b73624f94bf2f3599bcc522cae625d7/raw/e0b35a3e20b6890ee353cd3845f52f25168a6d29/qbsdiff-flamegraph-libxul-no-parallel.svg) for the delta compressor, comparing two different versions of firefox libxul.so (around 142 MiB), with parallel searching disabled. The algorithm constructs a suffix array at first (using `SuffixArray::new()` powered by Yuta Mori's [divsufsort](https://github.com/y-256/libdivsufsort) in C, taking roughly 40% of time), then searches exact matches one by one (using `SuffixArray::search_lcp()`, roughly 40% of time), then handle similarity bytes surround each exact match, and finally bzip all outputs together (using libbz2, roughly 10% of time).

It seems that [cancel-rs](https://github.com/wez/cancel-rs) requires computation task itself to check cancellation token periodically. I have no idea about how to insert checkpoints to the dedicated suffix array construting process. However, for following steps of the delta compressor, checkpoints could be simply inserted before searching each exact match to support cancellation. Similarly, for the delta patcher, we can just check cancellation token before every control instruction decoding process during iteration.

**Comment by yrashk** [comment]
On a tangentially related note, have you seen https://github.com/IlyaGrebnov/libsais?

**Comment by hucsmn** [comment]
> On a tangentially related note, have you seen https://github.com/IlyaGrebnov/libsais?

The [benchmarks](https://github.com/IlyaGrebnov/libsais/blob/master/Benchmarks.md) looks interesting. I'll investigate on it later, thanks for recommendation.

With a quick glance at their reference papers list, libsais seems to be based on [an improved version of pSACA-K](https://doi.org/10.1109/TC.2020.2972546), a parallel variant of SAIS. I have implemented a rust version of pSACAK years before, which is not idiomatically optimaized and is less performant than the single-threaded libdivsufsort, but still competitive to sais-lite. Optimizing suffix array construction algorithms is technecally tivial, and it requires great efforts on engineering. Making rust binding to a mature C implementation is much easier.
